openapi: 3.1.0
info:
  title: Convo
  version: '1.0'
  summary: The Convo Space
  description: Convo is the substrate that connects conversations and communities across the Internet.
  contact:
    name: Anudit Nagar
    email: nagaranudit@gmail.com
    url: 'https://theconvo.space'
  license:
    name: MIT
    url: 'https://github.com/anudit/convo/blob/main/LICENSE.md'
  termsOfService: 'https://theconvo.space/privacy-policy'
servers:
  - url: 'https://theconvo.space/api'
    description: Anudit Nagar
paths:
  /threads:
    parameters: []
    get:
      summary: GET Threads
      operationId: get-api-threads-threadId
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: string
          in: query
          name: threadId
          description: ThreadId unique to a thread
        - schema:
            type: string
          in: query
          name: url
          description: urlencoded link of a page
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          description: API Key obtained from the The Convo Space Dashboard
          required: true
      description: Fetch Metadata for Threads.
  /comments:
    get:
      summary: GET Comments
      tags: []
      responses:
        '200':
          description: OK
        '400':
          description: Invalid/Incomplete params
        '401':
          description: Invalid API key
        '500':
          description: Internal Server Error
      operationId: get-comments
      parameters:
        - schema:
            type: string
          in: query
          name: threadId
          description: Unique Id of the Thread.
        - schema:
            type: string
          in: query
          name: url
          description: '`encodeURIComponent` value of the Base Url of the page.'
        - schema:
            type: string
          in: query
          name: author
          description: Ethereum Address of the Author.
        - schema:
            type: boolean
          in: query
          name: latestFirst
          description: Show the most recent comments first.
        - schema:
            type: string
          in: query
          name: page
          description: Page Number for paginated requests.
        - schema:
            type: string
          in: query
          name: pageSize
          description: Page Size for paginated requests.
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          description: API Key obtained from the The Convo Space Dashboard
          required: true
      description: 'Get comments filtered for a specific Website, Author or Thread.'
    post:
      summary: Create a New Comment
      operationId: post-comments
      responses:
        '200':
          description: OK
        '400':
          description: Invalid/Incomplete params
        '401':
          description: Invalid API key
        '500':
          description: Internal Server Error
        '503':
          description: Invalid Auth
      description: Create a new comment.
      parameters:
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          required: true
          description: API Key obtained from the The Convo Space Dashboard
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                signerAddress:
                  type: string
                comment:
                  type: string
                url:
                  type: string
                threadId:
                  type: string
              required:
                - token
                - signerAddress
                - comment
                - url
                - threadId
        description: ''
    delete:
      summary: Delete a Comment
      operationId: delete-comments
      responses:
        '200':
          description: OK
        '400':
          description: Invalid/Incomplete params
        '401':
          description: Invalid API key
        '503':
          description: Invalid Auth
      description: Delete a specific Comment.
      parameters:
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          description: API Key obtained from the The Convo Space Dashboard
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                signerAddress:
                  type: string
                commentId:
                  type: string
  /identity:
    get:
      summary: GET Trust Store for an Identity
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  score:
                    type: number
                  success:
                    type: boolean
                  poh:
                    type: boolean
                  brightId:
                    type: boolean
                  poap:
                    type: number
                  ens:
                    type: boolean
                  idena:
                    type: boolean
                  cryptoScamDb:
                    type: boolean
                  unstoppableDomains:
                    type: boolean
                  uniswapSybil:
                    type: number
                  deepdao:
                    type: number
                  rabbitHole:
                    type: number
                required:
                  - score
                  - success
                  - poh
                  - brightId
                  - poap
                  - ens
                  - idena
                  - cryptoScamDb
                  - unstoppableDomains
                  - uniswapSybil
                  - deepdao
                  - rabbitHole
                x-examples:
                  example-1:
                    score: 37
                    success: true
                    poh: false
                    brightId: false
                    poap: 24
                    ens: true
                    idena: false
                    cryptoScamDb: false
                    unstoppableDomains: false
                    uniswapSybil: 0
                    deepdao: 0
                    rabbitHole: 1
              examples:
                Example Response to 0xd8da6bf26964af9d7eed9e03e53415d37aa96045:
                  value:
                    score: 0
                    success: true
                    poh: true
                    brightId: true
                    poap: 0
                    ens: true
                    idena: true
                    cryptoScamDb: true
                    unstoppableDomains: true
                    uniswapSybil: 0
                    deepdao: 0
                    rabbitHole: 0
        '401':
          description: Invalid API key
      operationId: get-identity
      parameters:
        - schema:
            type: string
          in: query
          name: address
          description: Ethereum Address
          required: true
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          description: API Key obtained from the The Convo Space Dashboard
          required: true
      description: Get the Trust Score for any Ethereum Address.
  /auth:
    get:
      summary: GET Authentication Token
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    minLength: 1
                required:
                  - success
                  - message
                x-examples:
                  example-1:
                    success: true
                    message: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMHg3MDdhQzM5MzdBOUIzMUMyMjVEOEMyNDBGNTkxN0JlOTdjYWI5RjIwIiwiaWF0IjoxNjE3NzY1MzEzLCJleHAiOjE2MTc4NTE3MTN9.6sb6lnC5RIy_JWidsYyGYrHE2fGvajBEaVh5ybwsvqE
              examples:
                Example Auth Result:
                  value:
                    success: true
                    message: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMHg3MDdhQzM5MzdBOUIzMUMyMjVEOEMyNDBGNTkxN0JlOTdjYWI5RjIwIiwiaWF0IjoxNjE3NzY1MzEzLCJleHAiOjE2MTc4NTE3MTN9.6sb6lnC5RIy_JWidsYyGYrHE2fGvajBEaVh5ybwsvqE
        '400':
          description: |-
            Recovered address from signature doesn't match signerAddress or signerAddress.

            signature or timestamp is missing/invalid.

            Request timestamp too old.
        '401':
          description: Invalid API key
        '500':
          description: Internal Server Error
      operationId: get-auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                signature:
                  type: string
                signerAddress:
                  type: string
                timestamp:
                  type: string
              required:
                - signature
                - signerAddress
                - timestamp
        description: ''
      description: GET Authentication Token for interacting with Convo's API
      parameters:
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          description: API Key obtained from the The Convo Space Dashboard
          required: true
  /validateAuth:
    get:
      summary: Validate an Authentication Token
      tags: []
      responses:
        '200':
          description: 'OK, Valid Auth Token'
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                    minLength: 1
                required:
                  - success
                  - message
                x-examples:
                  example-1:
                    success: true
                    message: Valid Auth Token
              examples:
                Example Validation Response:
                  value:
                    success: true
                    message: Valid Auth Token
        '400':
          description: |-
            Invalid Auth Token.

            signerAddress or token is missing/invalid.

            JWT Authentication error.
        '401':
          description: Invalid API key
        '500':
          description: Internal Server Error
      operationId: get-validateAuth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                signerAddress:
                  type: string
              required:
                - token
                - signerAddress
      description: Validate an Authentication Token.
      parameters:
        - schema:
            type: string
            default: CONVO
          in: query
          name: apikey
          description: API Key obtained from the The Convo Space Dashboard
          required: true
components:
  schemas: {}
  securitySchemes:
    apikey:
      name: CONVO
      type: apiKey
      in: query
tags:
  - name: thread
