name: "Run Docsearch Indexer"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 12 * *"

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Run Docsearch Indexer
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Setup Env
      env:
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: node ./genenv.js
    - name: Run Docsearch Indexer
      uses: addnab/docker-run-action@v3
      with:
        image: algolia/docsearch-scraper:latest
        run: docker run -it --env-file=.env.local -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
