name: "Run Docsearch Indexer"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 12 * *"

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Run Docsearch Indexer
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - name: Run Docsearch Indexer
      env:
        APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: docker run -i -e APPLICATION_ID=$APPLICATION_ID  -e API_KEY=$API_KEY -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
